# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

# Tock uses rustfmt's default configuration.
#
# This empty configuration file exists so that when rustfmt is run within this
# repository, it does not search parent directories for a rustfmt.toml file.
# This allows projects with their own rustfmt.toml file to include tock as a
# submodule without changing the behavior of `make prepush`.
