[package]
name = "s32k14x"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }

[features]
default = ["std"]
std = []