[package]
name = "imxrt10xx"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm7 = { path = "../../arch/cortex-m7" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }
